In [15]:
texts = [
            '2019 C.T. Bauer College Business Graduate Magna Cum Laude aspire Human Resources professional',
             'Aspiring Human Resources Professional Kudipudi'
]

In [19]:
tokens = [['2019', 'C.T.', 'Bauer', 'College', 'Business', 'Graduate', 'Magna', 'Cum', 'Laude', 'aspire', 'Human', 'Resources', 'Professional', 'aspire', 'Human', 'Human'],
['aspire', 'Human', 'Resources', 'Professional', 'aspire', 'aspire', 'kudipudi']]

In [20]:
vocabulary = [
     'College', 'Cum', 'Business', 'aspire', 'Human', 'Resources', 'Laude', 'professional', 'Bauer', 'Magna', 
     'Graduate', 'C.T.', '2019', 'Professional', 'Kudipudi']

matrix will be size(len(vocabulary), len(vocabulary))

In [21]:
import numpy as np
mat = np.zeros((len(vocabulary),len(vocabulary)))
for i, token1 in enumerate(tokens[0]):
    for j, token2 in enumerate(tokens[0]):
        if i != j:
            index1, index2 = vocabulary.index(token1), vocabulary.index(token2)
            mat[index1][index2] += 1
print(mat)

[[0. 1. 1. 2. 3. 1. 1. 0. 1. 1. 1. 1. 1. 1. 0.]
 [1. 0. 1. 2. 3. 1. 1. 0. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 0. 2. 3. 1. 1. 0. 1. 1. 1. 1. 1. 1. 0.]
 [2. 2. 2. 2. 6. 2. 2. 0. 2. 2. 2. 2. 2. 2. 0.]
 [3. 3. 3. 6. 6. 3. 3. 0. 3. 3. 3. 3. 3. 3. 0.]
 [1. 1. 1. 2. 3. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 2. 3. 1. 0. 0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 2. 3. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 2. 3. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0.]
 [1. 1. 1. 2. 3. 1. 1. 0. 1. 1. 0. 1. 1. 1. 0.]
 [1. 1. 1. 2. 3. 1. 1. 0. 1. 1. 1. 0. 1. 1. 0.]
 [1. 1. 1. 2. 3. 1. 1. 0. 1. 1. 1. 1. 0. 1. 0.]
 [1. 1. 1. 2. 3. 1. 1. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [10]:
vocabulary.index('2019')

12